### ISSUE TITLE
Campo searchengine tabella proxy_searchengine

### ISSUE THREAD

**Issue by Cabbina** [f12defilippis/SemRanker#10]
Il campo searchengine dovrebbe chiamarsi aggregated_searchengine.

**Comment by f12defilippis** [comment]
La tabella proxy searchengine serve ad identificare l'oggetto proxy relativo ad un singolo motore di ricerca e questo oggetto viene utilizzato per gestire la logica di disponibilità del proxy sul motore di ricerca inteso come provider (Google, Yahoo, Bing, etc) e non sul motore di ricerca abbinato alle caratteristiche geografiche o di dispositivo.
