### ISSUE TITLE
Schedulazione fallita

### ISSUE THREAD

**Issue by Cabbina** [f12defilippis/SemRanker#16]
Questa notte alle 00:35 sarebbe dovuto partire il motore ma c'è stato un fail. Era la prima volta che non stoppavo e riavviavo l'applicazione dal giorno precedente.
Vedere log alle 00:35.

**Comment by f12defilippis** [comment]
@Cabbina Ho aggiunto un parametro sul file application.properties... Se non dovesse funzionare abbiamo altri modi altrettanto rapidi per risolvere questo problema
