### ISSUE TITLE
Data con orario impostato a 00:00:01

### ISSUE THREAD

**Issue by Cabbina** [f12defilippis/SemRanker#6]
### In alcuni casi sulle tabelle search_report, search_report_account e keyword_scan_summary nelle colonne date_firstseen, date_lastseen, date_closed e date l'orario riportato è 00:00:01.

**Inserire colonna date con l'ora di sistema su tutte le tabelle.**

**Comment by f12defilippis** [comment]
@Cabbina Il problema dipendeva dal fatto che quando andavo ad impostare la data a mezzanotte non impostavo anche i millisecondi e per questo motivo l'arrotondamento della data causava il disallineamento
