### ISSUE TITLE
Domini non corretti

### ISSUE THREAD

**Issue by Cabbina** [f12defilippis/SemRanker#7]
### In alcuni casi il dominio inserito non è corretto.

Ad esempio ".fnac" nel caso di url: "http://www4.fnac.com/a5569719/secrets-tome-141-search-engine-optimization-seo-secrets-danny-dover"

oppure

"/url" nel caso di url: "/url?q=http://www.secretkey.it/servizi"

**Comment by f12defilippis** [comment]
@Cabbina non sono riuscito a replicare, ho fatto un tentativo.. vediamo se si verifica di nuovo

**Comment by Cabbina** [comment]
Ci sono delle altre casistiche di domini non corretti, vedi:
.garmin.com http://www8.garmin.com/products/webupdater/howtoinstall.jsp
.hp.com http://www8.hp.com/de/de/drivers.html
.k9webprotection.com    http://www1.k9webprotection.com/getk9/download-software
.xen.com.au http://www3.xen.com.au/free-ebook-website-redesign-seo

**Comment by Cabbina** [comment]
Ho trovato un dominio creato in data odierna che contiene il "." davanti:

.software.ibm.com

ID 15248

Non ci sono url però legate a questo dominio sul DB

**Comment by f12defilippis** [comment]
@Cabbina Ho ampliato ancora l'espressione regolare... Vediamo se c'è ancora qualche tipologia di url che non copriamo.
