### ISSUE TITLE
Duplicati

### ISSUE THREAD

**Issue by Cabbina** [f12defilippis/SemRanker#8]
### Ci sono alcuni dati che sembrano duplicati sulla search_report_account.

Sembrerebbe che il motore abbia girato due volte utilizzando due proxy per effettuare la stessa ricerca.

Di seguito query per visualizzare i dati:

SELECT sra.id, position, k.text,dom.name FROM semranker.search_report_account sra
join keyword_scan_summary ksu
on keyword_scan_summary=ksu.id
join keyword_searchengine_account_domain kd
on ksu.keyword_search_engine_account_domain=kd.id
join keyword_searchengine ks
on keyword_searchengine=ks.id
join aggregated_searchengine ase
on aggregated_searchengine=ase.id
join searchengine se
on searchengine=se.id
join searchengine_country sc
on searchengine_country=sc.id
join keyword k
on keyword=k.id
join account_domain ac
on account_domain=ac.id
join domain dom
on domain=dom.id
where tld='it'
and position=14
order by position, keyword;

select \* from search_report_account where id in (9,43);

select \* from keyword_scan_summary where id in (6086,12825);

select \* from proxy where id in (308,314);

**Comment by f12defilippis** [comment]
@Cabbina anche questo problema dipendeva dal fatto che la data veniva impostata in modo non corretto e quindi il confronto non andava a buon fine creando dei duplicati.
